/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_LOBBS_PB_H_INCLUDED
#define PB_MESHTASTIC_LOBBS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) meshtastic_LoBBSUser_password_hash_t;
/* LoBBS User Record
 Stores user authentication information for the LoBBS system */
typedef struct _meshtastic_LoBBSUser {
    /* Username for the user account */
    char username[32];
    /* SHA256 hash of the user's password (32 bytes) */
    meshtastic_LoBBSUser_password_hash_t password_hash;
    /* User ID - deterministic hash derived from username */
    uint32_t uid;
} meshtastic_LoBBSUser;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoBBSUser_init_default        {"", {0, {0}}, 0}
#define meshtastic_LoBBSUser_init_zero           {"", {0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoBBSUser_username_tag        1
#define meshtastic_LoBBSUser_password_hash_tag   2
#define meshtastic_LoBBSUser_uid_tag             3

/* Struct field encoding specification for nanopb */
#define meshtastic_LoBBSUser_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   username,          1) \
X(a, STATIC,   SINGULAR, BYTES,    password_hash,     2) \
X(a, STATIC,   SINGULAR, UINT32,   uid,               3)
#define meshtastic_LoBBSUser_CALLBACK NULL
#define meshtastic_LoBBSUser_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSUser_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoBBSUser_fields &meshtastic_LoBBSUser_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_LOBBS_PB_H_MAX_SIZE           meshtastic_LoBBSUser_size
#define meshtastic_LoBBSUser_size                73

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
